### ISSUE TITLE
Scaffold a new component with template

### ISSUE THREAD

**Issue by AaronKow** [PebbleRoad/cobblestone#15]
Since there is multiple files (e.g. `.vue` `.md`, `stories.js`, `test.js`) required to be create every single time we want a new component.

Good to have, say if we have an npm command that able to scaffold the files automatically like

```bash
$ npm run component Button

or

$ yarn component Button
```

**Comment by kyleoliveiro** [comment]
Yes, it is planned as part of issue #5

**Comment by kyleoliveiro** [comment]
Closed by https://github.com/PebbleRoad/cobblestone/pull/16
